### ISSUE TITLE
Plugin is not compatible with Idea 2020.3

### ISSUE THREAD

**Issue by kortov** [TestShiftProject/test-cube#1]
![image](https://user-images.githubusercontent.com/6348215/105577085-da0eaa00-5d90-11eb-9079-9039ef446f0c.png)

**Comment by lacinoire** [comment]
Hey kortov!

Thanks for making me aware 😊
I fixed my build for IntelliJ 2020.3 & published a new version on the Marketplace: https://plugins.jetbrains.com/plugin/14678-test-cube/versions/stable/109865
Could you check if it works for you now? 

Let me know if you need any further help getting started! 😄

**Comment by kortov** [comment]
Yes, it's installable from marketplace, thanks

**Comment by kortov** [comment]
relates to b715fd6aa1929abd7023ac286688f3b1c8cc6633
