### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by marabesi** [TestShiftProject/test-cube#18]
Hello there, I was trying to use the plugin in the latest version of intellij but i got the following error:

![image](https://github.com/TestShiftProject/test-cube/assets/2129872/3f97148e-2705-4236-b105-30974bf42d78)

I believe this error is also related with the plugin upgrade that makes the [pipeline to fail](https://github.com/TestShiftProject/test-cube/actions/runs/6585129592/job/17890974902). But it seems that updating the plugin requires java version changes as well.

Is there any plans to make it available in the jetbrains store again?

**Comment by lacinoire** [comment]
Hey @marabesi !

Thanks for reaching out :)
I did get it to build on the new IntelliJ end of last year again.

Let me have a look later this week that I update it to the latest IntelliJ version & also publish it accordingly.
Then I'll ping back here!



Is the project you want to use TestCube on public by any chance? :)
Setup can be a bit finnicky (maven / gradle). If you can point me to the project or tell me which maven / gradle version + Java version you use, then I can also start testing with a similar project :)

**Comment by marabesi** [comment]
Thanks for replying, I can try to give a hand with a contribution as well.

I am planning to use this first in a closed source project and see how the tool behaves, not something open atm, I am just exploring.

I got to know the project from this [paper](https://link.springer.com/article/10.1007/s10664-021-10094-2)

**Comment by lacinoire** [comment]
Hey @marabesi,

Could you try the new version on the marketplace: https://plugins.jetbrains.com/plugin/14678-test-cube/versions/stable/470155
And tell me this one works out for you? :)

I have tested it on my usual example project (jsoup, with Maven) and it runs fine.
Should the plugin run, but not succeed in generating tests, please ping me again so we can try getting it to run :)

**Comment by marabesi** [comment]
Thanks for that, it is working perfectly, I am already amplifying my tests.
