### ISSUE TITLE
Building test-cube

### ISSUE THREAD

**Issue by abolfazl-sh** [TestShiftProject/test-cube#4]
Hello.
I'm trying to build test-cube. When I run "runIde", after downloading some dependency, it starts download "IdealC-2021.2.1.zip".
Is it ok?
I am using IdeaC-2021.2.1 as my IDE.
Thanks in advance.

**Comment by lacinoire** [comment]
Yeah that is how it should be 🙂
This is only the first time you build / any time you update to a new IntelliJ version.
It'll not reuse your own IntelliJ installation, as you might be targeting a different version of IntelliJ.

Carolin Brandt

PhD Student // she/her
TU Delft // EEMCS // Software Engineering Research Group // TestShift Project <https://testshiftproject.github.io/>
E ***@***.*** ***@***.***> // T https://twitter.com/laci_noire <https://twitter.com/laci_noire> // W https://carolin-brandt.de/ <https://carolin-brandt.de/>

**Comment by abolfazl-sh** [comment]
After a massive downloading, something go wrong.
The error log is as follow:
```
C:\Users\abolfazl\IdeaProjects\GitProjects\src\main\java\org\testshift\testcube\amplify\AmplifyTestMarkerContributor.java:5: error: cannot access com.intellij.execution.lineMarker.RunLineMarkerContributor
import com.intellij.execution.lineMarker.RunLineMarkerContributor;
                                        ^
  bad class file: C:\Users\abolfazl\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2021.2.1\fb8e0c8f941235e03802029fb64f458df3d2823c\ideaIC-2021.2.1\lib\platform-impl.jar(com/intellij/execution/lineMarker/RunLineMarkerContributor.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
As it's obvious, something is wrong with the versions, but what's that? 
(it's using the IDE was downloaded by itself and some file version is wrong. It is a little confusing)
