### ISSUE TITLE
How check modified project

### ISSUE THREAD

**Issue by abolfazl-sh** [TestShiftProject/test-cube#5]
I have modified some part of project.
How  I check the test-cube after some modification?
Should I manually install plugin and check it? (or there is an easy way?)

**Comment by abolfazl-sh** [comment]
I have found it ( just write for visitors).
You can check it by running "runIdeForUiTests".

**Comment by lacinoire** [comment]
I normally use "runIde" 🙂
Not sure what "ForUiTests" does in addition but good if it works for you 👍🏼

For general IntelliJ Plugin Knowledge I find the official documentation a better and better source: https://plugins.jetbrains.com/docs/intellij/welcome.html 😊
